---
- hosts: server
  # connection: local
  pre_tasks:
    - name: "check distridution"
      debug:
        var: "ansible_distribution"
      failed_when: ansible_distribution != 'Ubuntu'

    - name: "check architecture"
      debug:
        var: "ansible_architecture"
      failed_when: ansible_architecture != 'x86_64'

  roles:
    - role: common
    - role: docker
    - role: docker-compose
    - role: docker-machine
