---
- name: "dl"
  get_url:
    url: "{{ source_url }}"
    dest: "{{ install_path }}"
  when: install_docker_compose_v2 == False

- name: "mkdir"
  file:
    path: "{{ docker_compose_v2.install_dir }}"
    state: directory

- name: "dl"
  get_url:
    url: "{{ docker_compose_v2.source_url }}"
    dest: "{{ docker_compose_v2.install_dir }}/docker-compose"

