---
- name: "chmod"
  file:
    path: "{{ install_path }}"
    mode: "0775"

- name: "mkdir {{ completion_destdir }}"
  file:
    path: "{{ completion_destdir }}"
    state: directory

- name: "dl completion"
  get_url:
    url: "{{ completion_url }}/{{ item }}"
    dest: "{{ completion_destdir }}/{{ item }}"
  with_items: "{{ completion_files }}"

- name: "add PS1 docker-machime prompt"
  blockinfile:
    path: "~/.bashrc"
    block: >
      PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__docker_machine_ps1)\$ '
    backup: yes