---
- name: "apt update"
  apt:
    update_cache: yes

- name: "apt upgrade"
  apt:
    upgrade: "yes"

- name: "install depends to add-3rd party repository"
  apt:
    name:
    - "curl"
    - "ca-certificates"
    - "gnupg"
