---
- name: package.yaml
  include_tasks: package.yaml

- name: config.yaml
  include_tasks: config.yaml

- name: service.yaml
  include_tasks: service.yaml

- name: compose-cli.yaml
  include_tasks: compose-cli.yaml
  when: install_compose_cli == True

- name: gvisor.yaml
  include_tasks: gvisor.yaml
  when: install_gvisor == True
